misc/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misc/ecommerce/web/urls.py
from django.urls import path
from web.views.account import *
from web.views.category import *
from web.views.product import *
from web.views.cart import *
app_name = "web"

# views
urlpatterns = [
    # Landing Page
    path("", SignIn.as_view(), name="signin"),
    path("home/", Home.as_view(), name="home"),

    #Login Actions 
    path("signin/", SignIn.as_view(), name="signin"),
    path("signout/", SignOut.as_view(), name="signout"),
    

    #Category
    path('category/', CategoryView.as_view(), name='category'),
    path('category/create/', CategoryCreate.as_view(), name='create_category'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='update_category'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='delete_category'),
    path('category/<int:pk>/view/', CategoryDetail.as_view(), name='view_category'),
    
    #category disable enable fun()
    path('changestatus/', change_status, name="change_status"),
    
    #Product
    path('product/', ProductView.as_view(), name='product'),
    path('product/create/',ProductCreate.as_view(),name='create_product'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='update_product'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='delete_product'),

    #list
    path('product_image/', ProductImageView.as_view(), name='product_image'),


    #search
    path('search/',search,name="search"),

    #variant
    path('product/varaint/',ProductVariantView.as_view(), name='product_variant'),
    path('product/variant/create/',ProductVariantCreate.as_view(),name='product_variant_create'),
    

    #shop
    path('shop/',ShopView.as_view(),name="shop"),


    #Cart
    path("shop/cart/",CartView.as_view(), name="cart"),
    path("shop/cart/add/",AddToCartView.as_view(), name="add_to_cart"),
]

misc/ecommerce/web/forms/category.py
from django import forms
from web.models import Category

class CategoryForm(forms.ModelForm):
    title = forms.CharField(
        label='Title',max_length=150,required=True,
        widget=forms.TextInput(attrs={'autocomplete':'off'}),
        error_messages={ 'required': 'The title should not be empty' }
    )

    description = forms.CharField(label='Description',max_length=150,required=True,widget=forms.Textarea(attrs={'autocomplete':'off'}),
        error_messages={ 'required': 'The Description should not be empty' })
    
    class Meta:
        model = Category
        fields = ['title','description']

misc/ecommerce/web/views/category.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, View
from web.forms.category import CategoryForm
from web.helper import renderfile, is_ajax, LogUserActivity
from web.models import Category
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import *
from web.constantvariables import PAGINATION_PERPAGE
from django.shortcuts import get_object_or_404
from django.db import transaction
import json

class CategoryView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context, response = {}, {}
        page = int(request.GET.get('page', 1))
        categories = Category.objects.all()

        paginator = Paginator(categories, PAGINATION_PERPAGE)
        try:
            categories = paginator.page(page)
        except PageNotAnInteger:
            categories = paginator.page(1)
        except EmptyPage:
            categories = paginator.page(paginator.num_pages)

        context['categories'], context['current_page'] = categories, page
        if is_ajax(request=request):
            response['status'] = True
            response['pagination'] = render_to_string("web/category/pagination.html",context=context,request=request)
            response['template'] = render_to_string('web/category/category_list.html', context, request=request)
            return JsonResponse(response)
        context['form']  = CategoryForm()
        return renderfile(request, 'category', 'index', context)
    
class CategoryCreate(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        data = {}
        form = CategoryForm()
        print(form)
        context = {'form': form, 'id': 0}
        
        data['status'] = True
        data['title'] = 'Create Categoryy'
        data['template'] = render_to_string('web/category/category_form.html', context, request=request)
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        response = {}
        form = CategoryForm(request.POST or None)
        if form.is_valid():
                with transaction.atomic():
                    title = request.POST.get('title', None)
                    description = request.POST.get('description', None)
                    if not Category.objects.filter(title=title).exists():
                        title = Category.objects.create(title=title,description=description)
                        response['status'] = True
                        response['message'] = 'Added successfully'
                    else:
                        response['status'] = False
                        response['message'] = 'Category Already exists'
        else:
            response['status'] = False
            context = {'form': form}
            response['title'] = 'Edit Category'
            response['valid_form'] = False
            response['template'] = render_to_string('web/category/category_form.html', context, request=request)
        return JsonResponse(response)
    

class CategoryUpdate(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        id = kwargs.get('pk', None)
        data = {}
        obj = get_object_or_404(Category, id = id)
        form = CategoryForm(instance=obj)
        context = {'form': form, 'id': id}
        data['status'] = True
        data['title'] = 'Edit Category'
        data['template'] = render_to_string('web/category/category_form.html', context, request=request)
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        data, response = {} , {}
        id = kwargs.get('pk', None)
        obj = get_object_or_404(Category, id=id)
        previous_name = obj.title
        form = CategoryForm(request.POST or None, instance=obj)

        if form.is_valid():
            try:
                with transaction.atomic():
                    if Category.objects.filter(title__icontains=request.POST.get('title')).exclude(id=id).exists():
                        response['status'] = False
                        response['message'] = "title already exists"
                        return JsonResponse(response)
                    obj.title = request.POST.get('title' or None)
                    obj.description = request.POST.get('description' or None)
                    obj.save()

                    response['status'] = True
                    response['message'] = "Category updated successfully"
                    return JsonResponse(response)
                
            except Exception as dberror:
                response['message'] = "Something went wrong"
                response['status'] = True
        else:
            response['status'] = False
            context = {'form': form}
            response['title'] = 'Edit Category'
            response['valid_form'] = False
            response['template'] = render_to_string('web/category/category_form.html', context, request=request)
            return JsonResponse(response)
        
class CategoryDetail(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        id = kwargs.get('pk', None)
        data = {}
        obj = get_object_or_404(Category, id = id)
        context = {'form': obj, 'id': id}
        data['status'] = True
        data['title'] = 'View Category'
        data['template'] = render_to_string('web/category/category_view.html', context, request=request)
        return JsonResponse(data)
    
class CategoryDelete(LoginRequiredMixin,View):
    def post(self, request, *args, **kwargs):
        id = kwargs.get('pk', None)
        response = {}
        obj = get_object_or_404(Category, id = id)
        obj.delete()
        
        response['status'] = True
        response['message'] = "Category deleted successfully"
        return JsonResponse(response)
    
def change_status(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print('data===',data)
        category_id = data['id']
        is_active = data['is_active']
        category = get_object_or_404(Category, id=category_id)
        category.is_active = is_active
        category.save()
        response = {'status': 'success', 'is_active': category.is_active}
        return JsonResponse(response, status=200)
    else:
        response = {'status': 'error', 'message': 'Invalid request'}
        return JsonResponse(response, status=400)

misc/ecommerce/templates/web/category/category_form.html
<div class="formbg-inner">
    <div class="edit-category-form">
        {% if id %}
            <input type="hidden" value="{% url 'web:update_category' id %}" id="form_url" name="form_url">
        {% else %}
            <input type="hidden" value="{% url 'web:create_category' %}" id="form_url" name="form_url">
        {% endif %}            
        <div class="field padding-bottom--24">
            <label for="name">Name</label> {{ form.title }}
            <p class="text-danger mt-2 mb-0">{{ form.title.errors.as_text  }}</p>
        </div>
        <div class="field padding-bottom--24">
            <label for="name">description</label> {{ form.description }}
            <p class="text-danger mt-2 mb-0">{{ form.description.errors.as_text  }}</p>
        </div>
        <div class="field padding-bottom--24">
            <input class="category-submit" id="category-submit" type="submit" name="submit" value="Save">
        </div>
    </div>
</div>

misc/ecommerce/templates/web/category/category_list.html
{% load static %}
{% for category in categories %}
<tr>
    <td>{{forloop.counter0|add:categories.start_index}}</td>
    <td>{{category.title}}</td>
    <td>{{category.description}}</td>
  
    <td>
        <div class="form-check form-switch">
            <input class="form-check-input toggle-status" type="checkbox" role="switch" id="flexSwitchCheckDefault{{ category.id }}" data-id="{{ category.id }}" {% if category.is_active %}checked{% endif %}>
            <label class="form-check-label" for="flexSwitchCheckDefault{{ category.id }}">{{ category.is_active }}</label>
        </div>
    </td>
   
    <td>
        <a href="javascript:;" class="category-edit" id="category-edit" data-fancybox="" data-src="#category-popup" data-url="{% url 'web:update_category' category.id %}">
            <img src="{% static '/web/assets/images/edt_icon.svg' %}" alt="icon">
        </a>

        <a href="javascript:;" onclick="CategoryDelete({{category.id}})">
            <img src="{% static '/web/assets/images/dlt_icon.svg' %}" alt="icon">
        </a>

        <a href="javascript:;" class="category-edit" id="category-edit" data-fancybox="" data-src="#category-popup" data-url="{% url 'web:view_category' category.id %}">
            <img src="{% static '/web/assets/images/eye-svgrepo-com.svg' %}"  width="38" height="38" alt="icon">
        </a>
    </td>

<tr>
{% endfor %}

misc/ecommerce/templates/web/category/category_view.html
<div class="formbg-inner">
    <div class="edit-category-form">
        {% if id %}
            <input type="hidden" value="{% url 'web:view_category' id %}" id="form_url" name="form_url">
        {% endif %}            
        <div class="field padding-bottom--24">
            <label for="name">Name:</label> {{ form.title }} 
        </div>
        <div class="field padding-bottom--24">
            <label for="name">Description:</label> {{ form.description }}
        </div>
        <div class="field padding-bottom--24">
            <label for="name">Status:</label> {{ form.is_active }}
        </div>
    </div>
</div>

misc/ecommerce/templates/web/category/index.html
{% extends "web/layout/user_base.html" %} {% load static %} {% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">
        <input type="hidden" value="{% url 'web:category' %}" id="load_category">
        <div class="d-flex justify-content-between">
            <h1 class="page-block-title">Category List</h1>
            <div>
                <a class="add-category" id="create_category" data-fancybox="" data-src="#category-popup"  data-url="{% url 'web:create_category' %}">
                    <button>+ Add Category</button>
                </a>
            </div>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>Sl.NO</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Action</th>
                       
                    </tr>
                </thead>

                <tbody id="category-tbody">
                    {% include 'web/category/category_list.html' %}
                </tbody>
            </table>
        </div>
    </div>

    {% comment %} <div class="pagination-outer align-items-center justify-content-between d-flex" id="category-pagination">
        {% include 'web/category/pagination.html' %}
    </div> {% endcomment %}

    <div>
        <!-- Curriculum Add form starts-->
        <div class="add-category" id="category-popup" style="display:none;">
            <div class="pop-body" id="category-div">
                <div class="formbg-inner">
                    <form method="post" action="" class="CategoryForm" id="CategoryForm" name="CategoryForm">
                        {% csrf_token %}
                        <h2 class="padding-bottom--15" id="popup_head">Add Category</h2>
                        <div class="category-form" id="category-form-div">
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Curriculum Add form ends -->
    </div>
    
</div>
</div>
{% endblock body_block %} 
{% block page_script %}
<script src="{% static 'web/assets/js/category.js' %}?v={% now 'd_m_yH:i:s'%}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $(".toggle-status").on("change", function() {
            let categoryId = $(this).data("id");
            let isActive = this.checked;
            console.log("categoryId===",categoryId)
            console.log("isActive===",isActive)
            $.ajax({
                url: "{% url 'web:change_status' %}",
                type: "POST",
                data: JSON.stringify({
                    id: categoryId,
                    is_active: isActive
                }),
                contentType: "application/json",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}"
                },
                dataType: "json",
                success: function(data) {
                    if (data.status === "success") {
                        console.log("Status updated successfully");
                        
                    } else {
                        alert("Failed to update status");
                    }
                },
                error: function(xhr, status, error) {
                    console.error("An error occurred: " + error);
                    alert("Failed to update status");
                }
            });
        });
    });
</script>
{% endblock page_script %}