misc/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swift/urls.py
from django.urls import path
from swift.views.account import *
from swift.views.curriculum import *
from swift.views.course import *
from swift.views.prompt import *
from swift.views.tool_template import *
from swift.views.template_tool import *

app_name = "appswift"
# views
urlpatterns = [
    # Landing Page
    path("", SignIn.as_view(), name="signin"),
    path("home/", Home.as_view(), name="home"),

    #Login Actions 
    path("signin/", SignIn.as_view(), name="signin"),
    path("forgot-password/", ForgotPassword.as_view(),name="forgot_password"),
    path("signout/", SignOut.as_view(), name="signout"),

    #Curriculum
    path("curriculum/", CurriculumView.as_view(), name="curriculum"),
    path('curriculum/create/', CurriculumCreate.as_view(), name='create_curriculum'),
    path('curriculum/<int:pk>/update/', CurriculumUpdate.as_view(), name='update_curriculum'),
    path('curriculum/<int:pk>/delete/', CurriculumDelete.as_view(), name='delete_curriculum'),


    #Course
    path('course/', CourseView.as_view(), name='course'),
    # path('course/create/', CourseCreate.as_view(), name='create_course'),
    # path('course/<int:pk>/update/', CourseUpdate.as_view(), name='update_course'),
    # path('course/<int:pk>/delete/', CourseDelete.as_view(), name='delete_course'),
    
    #Prompt
    path('prompt/', PromptView.as_view(), name='prompt'),
    path('prompt/create/', PromptCreate.as_view(), name='create_prompt'),
    path('prompt/<int:pk>/update/', PromptUpdate.as_view(), name='update_prompt'),

    #PromptOut
    path('promptout/create/', PromptOutCreate.as_view(), name='create_promptout'),


    #ToolTemplate
    path('tooltemplate/create', ToolTemplateView.as_view(), name='tooltemplate_create'),
    path('tooltemplate/input-details/create',ToolTemplateInputCreateView.as_view(), name='tooltemplate_input_create'),
    
    path('templatetool/create',TemplateToolView.as_view(), name='template_tool_create'),

    path('tooltemplate/list',TemplateToolList.as_view(),name='tooltemplate_list'),
    path('tooltemplate/detail/<int:pk>/',TemplateToolDetail.as_view(),name='tooltemplate_form')
    
]

swift/views/account.py
import datetime
from django.views.generic import CreateView,View
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from swift.helper import renderfile
import pdb
import json
from django.http import JsonResponse
from datetime import date
from django.db import transaction
from django.db.models import Q, Prefetch, Count
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.template import loader
from django.utils import timezone
from django.core.paginator import Paginator
from django.core.cache import cache
from django.utils.http import url_has_allowed_host_and_scheme
from swift.forms.account import SignInForm
from django.db.models.functions import Concat  
from django.db.models import Value as V
from django.db.models import CharField
from itertools import chain
from operator import attrgetter
#from swift.models import CREATE,  UPDATE, SUCCESS, FAILED, DELETE, READ
from swiftteacher.settings import ACTIVITY_PASSWORD, ALLOWED_IP
#from swift.models import ACTION_TYPES, ACTION_STATUS
from django.core.paginator import *
import calendar
#from hisensehr.tasks import send_email_to_users
from swift.models import User,ToolType
from swift.helper import emailhelper


class SignIn(CreateView):
    template_name = "swift/account/index.html"
    
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect( reverse('appswift:home' ) )
        
        cache.set('next', request.GET.get('next', None))
        datas = { 'form' : SignInForm() }
        return render(request, self.template_name, datas)

    def post(self, request, *args, **kwargs):
        datas = {}
        form = SignInForm(request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST.get('email'), password=request.POST.get('password'))
            if user is not None and user.is_active:
                login(self.request, user)
                next_url = cache.get('next')
                if next_url:
                    cache.delete('next')
                    if not url_has_allowed_host_and_scheme(url=next_url, allowed_hosts={request.get_host()}, require_https=request.is_secure()):
                        return HttpResponseRedirect(reverse('appswift:home'))
                    else:
                        return HttpResponseRedirect(next_url)
                else:
                    return HttpResponseRedirect(reverse('appswift:home'))
            messages.error(request,"Invalid Login Details")
            return HttpResponseRedirect( reverse('appswift:signin') )
        else:
            email = request.POST.get('email')
            if User.objects.filter(email=email, is_active=False).exists():
                messages.error(request,"Your account is not active")
            else:
                if not request.POST.get('email'):
                    messages.error(request,"Email is required")
                elif not request.POST.get('password'):
                    messages.error(request,"Password is required")
                else:
                    messages.error(request,"Invalid Login Details")
        datas['form'] = form
        return render(request, self.template_name, datas)


class Home(LoginRequiredMixin, CreateView):
    template_name = "swift/account/home.html"
    def get(self, request, *args, **kwargs):
        # if self.request.user.is_authenticated:
        #     return HttpResponseRedirect( reverse('appswift:home' ) )
        cache.set('next', request.GET.get('next', None))
        
        datas = { 'form' : SignInForm() }
        return render(request, self.template_name, datas)
    
class HomeLayout(LoginRequiredMixin,View):
    template_name = "swift/layout/user_base.html"
    def get(self, request, *args, **kwargs):
        tool_types = ToolType.objects.all()
        print('=====',tool_types)

        context ={
            'tool_types':tool_types,
        }
        return render(request, self.template_name,context)



class SignOut(CreateView):
    def get(self, request, *args, **kwargs):
        logout(self.request)
        request.session.flush()
        return HttpResponseRedirect( reverse('appswift:signin') )


class ForgotPassword(View):
    def get(self, request, *args, **kwargs):
        return renderfile(request,'account','forgot_password')
    
    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            scheme = request.is_secure() and "https://" or "http://"
            current_site = get_current_site(request)
            domainlink = scheme + current_site.domain
            mail_subject = 'Swift - Forgot Password'
            template = loader.get_template(
                'hisensehr/email-layout/acc_active_email.html')
            html_temp = template.render({
                'domain': domainlink,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user)}, request)

            content_replace = {"NAME": str(user.first_name).capitalize() + " " + str(user.last_name).capitalize(), "LINK": html_temp}
            if emailhelper(request, mail_subject, 3, content_replace, email,action="forget-password"):
                messages.success(request, 'Reset Password Link Was Sent To Your Email!')
                return HttpResponseRedirect( reverse('appswift:signin') )
            else:
                messages.error(request, "Something went wrong")
                return HttpResponseRedirect( reverse('appswift:forgot_password') )
        except User.DoesNotExist:
            email = request.POST.get('email')
            if not email:
                messages.error(request, "Email is required")
            else:
                messages.error(request, "User not found with this email")
            return renderfile(request, 'account', 'forgot_password')

"""def reset_password_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        
        if user:
            return renderfile(request, 'account', 'reset_password', {'user': user.id})
        else:
            return renderfile(request, '', '404', {})
    else:
        return renderfile(request, '', '404', {})

def change_password(request):
    userid = request.POST.get('user')
    pwd = request.POST.get('password1')
    cpwd = request.POST.get('password2')
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        user = None
    if not pwd:
        messages.error(request, "Password cannot be empty")
        return renderfile(request, 'account', 'reset_password', {'user': user.id})
    if pwd == cpwd:
        if len(pwd)>=6:
            with transaction.atomic():
                if user:
                    user.set_password(pwd)
                    user.save()
                    # Profile.objects.filter(user=user).update(password_str=pwd)
                    messages.success(request, "Password Changed Successfully")
                    return HttpResponseRedirect( reverse('appswift:signin') )
                else:
                    messages.error(request, "Something went wrong")
                    return renderfile(request, 'account', 'reset_password', {'user': user.id})
        else:
            messages.error(request, "Password must be atleast 8 characters")
            return renderfile(request, 'account', 'reset_password', {'user': user.id})
    else:
        messages.error(request, "New password and confirm password should be same")
        return renderfile(request, 'account', 'reset_password', {'user': user.id})


    
class ActivityLogView(View):
    def get(self, request, *args, **kwargs):
        return renderfile(request,'utils','activity_log')
    
    def post(self, request, *args, **kwargs):
        context = {}
        context['permission_granted'] = False
        #print("--------",ACTIVITY_PASSWORD)
        if ACTIVITY_PASSWORD:
            user_password = request.POST.get('activity_password')
            try:
                #print(ACTIVITY_PASSWORD,"----", user_password)
                if user_password == ACTIVITY_PASSWORD:
                    context['permission_granted'] = True
                    context['action_types'] = ACTION_TYPES
                    context['action_statuses'] = ACTION_STATUS
                    context['employees'] =  User.objects.only('id','first_name','last_name').exclude(is_superuser=True).order_by('first_name')
                else:
                    messages.error(request, "No permission to do the action")
            except Exception as e:
                messages.error(request, "No permission to do the action")
        else:
            messages.error(request, "No permission to do the action")
        return renderfile(request,'utils','activity_log', context)
    
class FetchActivityLogView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        data = {}
        conditions = {}
        page = request.GET.get('page', 1)
        employee = request.GET.get('employee')
        action = request.GET.get('action')
        status = request.GET.get('status')
        from_date = request.GET.get('from_date')

templates/swift/layout/menu.html
{% load static %}
<div class="sidebar-content">
    <div class="sidebar-content-wrapper">
        <div class="logo-box">
            <h1 class="logo-full">LOGO</h1>
            <h1 class="logo-collapsed">L</h1>
        </div>
        <nav>
            <ul class="sidebar-link-list">
                <li class="sidebar-item active">
                    <a href="{% url 'appswift:home' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">User</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link sub-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Settings</span>
                        <div class="drop-arrow">
                            <span class="icon-Vector-2"></span>
                        </div>
                    </a>
                    <ul class="sub-menu">
                        <li class="submenu-list">
                            <a href="{% url 'appswift:curriculum' %}" class="submenu-item">Curriculum</a>
                        </li>
                        <li class="submenu-list">
                            <a href="{% url 'appswift:course' %}" class="submenu-item">Course</a>
                        </li>
                        <li class="submenu-list">
                            <a href="{% url 'appswift:prompt' %}" class="submenu-item">Prompt</a>
                        </li>
                        
                    </ul>
                </li>

                <li class="sidebar-item">
                    <a href="#" class="sidebar-link sub-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">AI Tools</span>
                        <div class="drop-arrow">
                            <span class="icon-Vector-2"></span>
                        </div>
                    </a>
                    <ul class="sub-menu">
                        <li class="submenu-list">
                            <a href="{% url 'appswift:tooltemplate_create' %}" class="submenu-item">Tool Template</a>
                        </li>    
                        <li class="submenu-list">
                            <a href="{% url 'appswift:template_tool_create' %}" class="submenu-item">Tool create</a>
                        </li> 
                        
                    </ul>
                </li>
                
                {% comment %} <li class="sidebar-item">
                    <a href="#" class="sidebar-link sub-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Tools</span>
                        <div class="drop-arrow">
                            <span class="icon-Vector-2"></span>
                        </div>
                    </a>
                    <ul class="sub-menu">
                        {% for i in tool_types %}
                        <li class="submenu-list">
                            <a href="" class="submenu-item">{{i.custom_tool_name}}</a>
                        </li>    
                       {% endfor %}
                        
                    </ul>
                </li> {% endcomment %}

                <li class="sidebar-item">
                    <a href="{% url 'appswift:tooltemplate_list' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Tool List</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="{% url 'appswift:signout' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
        </div>
    </div>