misc/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misc/ecommerce/web/urls.py
from django.urls import path
from web.views.account import *
from web.views.category import *
from web.views.product import *
from web.views.cart import *
app_name = "web"

# views
urlpatterns = [
    # Landing Page
    path("", SignIn.as_view(), name="signin"),
    path("home/", Home.as_view(), name="home"),

    #Login Actions 
    path("signin/", SignIn.as_view(), name="signin"),
    path("signout/", SignOut.as_view(), name="signout"),
    

    #Category
    path('category/', CategoryView.as_view(), name='category'),
    path('category/create/', CategoryCreate.as_view(), name='create_category'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='update_category'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='delete_category'),
    path('category/<int:pk>/view/', CategoryDetail.as_view(), name='view_category'),
    
    #category disable enable fun()
    path('changestatus/', change_status, name="change_status"),
    
    #Product
    path('product/', ProductView.as_view(), name='product'),
    path('product/create/',ProductCreate.as_view(),name='create_product'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='update_product'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='delete_product'),

    #list
    path('product_image/', ProductImageView.as_view(), name='product_image'),


    #search
    path('search/',search,name="search"),

    #variant
    path('product/varaint/',ProductVariantView.as_view(), name='product_variant'),
    path('product/variant/create/',ProductVariantCreate.as_view(),name='product_variant_create'),
    

    #shop
    path('shop/',ShopView.as_view(),name="shop"),


    #Cart
    path("shop/cart/",CartView.as_view(), name="cart"),
    path("shop/cart/add/",AddToCartView.as_view(), name="add_to_cart"),
]

misc/ecommerce/templates/web/layout/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/web/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/web/assets/css/default.css' %}">
    <link rel="stylesheet" href="{% static '/web/assets/css/reset.css' %}">
    <link rel="stylesheet" href="{% static '/web/assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/web/assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static '/web/assets/css/custom.css'%}">
</head>
<body>
    {% block body_block %}
    {% endblock %}
    <script src="{% static '/web/assets/js/jquery.min.js'%}"></script>
    <script src="{% static '/web/assets/js/bootstrap.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    {% block page_script %}
    {% endblock %}
</body>
</html>

misc/ecommerce/templates/web/layout/menu.html
{% load static %}
<div class="sidebar-content">
    <div class="sidebar-content-wrapper">
        <div class="logo-box">
            <h1 class="logo-full">Ecommerce</h1>
            <h1 class="logo-collapsed">E</h1>
        </div>
        
        {% if request.user.is_superuser == True %}
        
        <nav>
            <ul class="sidebar-link-list">
                <li class="sidebar-item active">
                    <a href="" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'web:category' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Category</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="{% url 'web:create_product' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Create Product</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="{% url 'web:product' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Products</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="{% url 'web:product_image' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Product Image</span>
                    </a>
                </li>
                
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link sub-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'swift/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'swift/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Variant</span>
                        <div class="drop-arrow">
                            <span class="icon-Vector-2"></span>
                        </div>
                    </a>
                    <ul class="sub-menu">
                        <li class="submenu-list">
                            <a href="{% url 'web:product_variant' %}" class="submenu-item">Variants</a>
                        </li>
                    </ul>
                </li>
                
                <li class="sidebar-item">
                    <a href="{% url 'web:signout' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Logout</span>
                    </a>
                </li> 
            </ul>
        </nav>
        
        {% else %}
        
        <nav>
            <ul class="sidebar-link-list">
                <li class="sidebar-item active">
                    <a href="" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Dashboard</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="{% url 'web:shop' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Shop</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="{% url 'web:cart' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Cart</span>
                    </a>
                </li>
                
                <li class="sidebar-item">
                    <a href="{% url 'web:signout' %}" class="sidebar-link">
                        <span class="menu-icon">
                            <img class="icon-dark" src="{% static 'web/assets/images/dashboard.svg' %}">
                            <img class="icon-white" src="{% static 'web/assets/images/dashboard-white.svg' %}">
                        </span>
                        <span class="menu-item">Logout</span>
                    </a>
                </li>

            </ul>
        </nav>
        {% endif %}
        </div>
    </div>

misc/ecommerce/templates/web/layout/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/web/assets/css/bootstrap.min.css'%} ">
    <link rel="stylesheet" href="{% static '/web/assets/css/default.css'%}">
    <link rel="stylesheet" href="{% static '/web/assets/css/reset.css'%}">
    <link rel="stylesheet" href="{% static '/web/assets/css/main.css'%}">
    <link rel="stylesheet" href="{% static '/web/assets/css/responsive.css'%}">
    <link rel="stylesheet" href="{% static '/web/assets/css/custom.css'%}">
    <link href="{% static '/web/assets/css/jquery.fancybox.min.css' %}" rel="stylesheet">
    <link href="{% static '/web/assets/css/magnific-popup.css' %}" rel="stylesheet">
</head>
<body>
    <div class="main-container">
    <div class="side-bar">
        {% include 'web/layout/menu.html' %}
        {% include 'web/status_message.html' %}
    </div>
    <div class="main-panel">
        <div class="top-bar">
            <div class="top-bar-left">
                <div class="toggle-btn">
                    <span class="icon-menu_icon"></span>
                </div>
                <div class="mobile-btn">
                    <span class="icon-menu_icon"></span>
                </div>
            </div>
            
            <ul class="top-bar-right">
                <li class="profile-avatar">
                    <img src="{% static 'web/assets/images/default-avatar.jpg' %}" alt="image">
                </li>
            </ul>
            
        </div>
        <div class="content">
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
    </div>

    </div>
    <script src="{% static 'web/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'web/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'web/assets/js/main.js' %}"></script>
    <script src="{% static 'web/assets/js/jquery.fancybox.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    {% block page_script %}
    {% endblock %}
</body>
</html>