misc/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misc/ecommerce/web/urls.py
from django.urls import path
from web.views.account import *
from web.views.category import *
from web.views.product import *
from web.views.cart import *
app_name = "web"

# views
urlpatterns = [
    # Landing Page
    path("", SignIn.as_view(), name="signin"),
    path("home/", Home.as_view(), name="home"),

    #Login Actions 
    path("signin/", SignIn.as_view(), name="signin"),
    path("signout/", SignOut.as_view(), name="signout"),
    

    #Category
    path('category/', CategoryView.as_view(), name='category'),
    path('category/create/', CategoryCreate.as_view(), name='create_category'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='update_category'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='delete_category'),
    path('category/<int:pk>/view/', CategoryDetail.as_view(), name='view_category'),
    
    #category disable enable fun()
    path('changestatus/', change_status, name="change_status"),
    
    #Product
    path('product/', ProductView.as_view(), name='product'),
    path('product/create/',ProductCreate.as_view(),name='create_product'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='update_product'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='delete_product'),

    #list
    path('product_image/', ProductImageView.as_view(), name='product_image'),


    #search
    path('search/',search,name="search"),

    #variant
    path('product/varaint/',ProductVariantView.as_view(), name='product_variant'),
    path('product/variant/create/',ProductVariantCreate.as_view(),name='product_variant_create'),
    

    #shop
    path('shop/',ShopView.as_view(),name="shop"),


    #Cart
    path("shop/cart/",CartView.as_view(), name="cart"),
    path("shop/cart/add/",AddToCartView.as_view(), name="add_to_cart"),
]

misc/ecommerce/web/forms/product.py
from django import forms
from web.models import Category,Product,ProductMedia,ProductVariant
from django.forms import inlineformset_factory


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category','name','description','p_keyword',]
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control','required':'True'}),
            'name': forms.TextInput(attrs={'class': 'form-control','required':'True'}),
            'description': forms.Textarea(attrs={'class': 'form-control','required':'True'}),
            'p_keyword': forms.Textarea(attrs={'class': 'form-control','required':'True'}),
            
        }

class ProductMultipleImage(forms.ModelForm):
    class Meta:
            model = ProductMedia    
            fields = ['image','is_default']
            widgets = {
                'image': forms.FileInput(attrs={'class': 'form-control','required':'True'}),
                'is_default': forms.CheckboxInput(attrs={'class': 'checkbox'}),
            }


MultipleImageInputFormFormSet = inlineformset_factory(
    Product,
    ProductMedia,
    form=ProductMultipleImage,
    extra=2,
    can_delete=True,
)

class ProductVariantForm(forms.ModelForm):
    class Meta:
          model = ProductVariant
          fields = ['product','variant_name','description','quantity','sale_price','image']
          widgets = {
               'product': forms.Select(attrs={'class': 'form-control','required':'True'}),
               'variant_name': forms.TextInput(attrs={'class': 'form-control','required':'True'}),
               'description': forms.Textarea(attrs={'class': 'form-control','required':'True'}),
               'quantity': forms.NumberInput(attrs={'class': 'form-control','required':'True'}),
               'sale_price': forms.NumberInput(attrs={'class': 'form-control','required':'True'}),
               'image': forms.FileInput(attrs={'class': 'form-control','required':'True'}),
          }
          

misc/ecommerce/web/views/cart.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, View
from django.urls import reverse
from web.forms.product import *
from web.helper import renderfile, is_ajax, LogUserActivity
from web.models import Category,Product,Cart
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import *
from web.constantvariables import PAGINATION_PERPAGE
from django.shortcuts import get_object_or_404,render,redirect
from django.db import transaction
from django.db.models import Q


class CartView(LoginRequiredMixin, View):
    template_name = "web/product/cart.html"
    def get(self, request):
        user = self.request.user
        cart_items = Cart.objects.filter(user=user)
        cart_total = float(sum(item.get_total_price() for item in Cart.objects.filter(user=user)))

        context = {
            "cart_items": cart_items,
            "cart_total": cart_total,
        }
        return render(request, self.template_name, context)



class AddToCartView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return JsonResponse({'message': 'User not authenticated'}, status=401)
        user = self.request.user
        quantity = request.GET.get('quantity', 1)
        is_cart=request.GET.get("update",'')
        print(is_cart,"==========")
        product_id = request.GET.get("product_id",'')
        product = get_object_or_404(ProductVariant, pk=product_id)

        cart_item, created = Cart.objects.get_or_create(
            user=user,
            product=product,
            defaults=({"quantity": quantity})
        )

        if not created:
            if is_cart:
                cart_item.quantity = int(quantity)
            else:
                cart_item.quantity += int(quantity)
            cart_item.save()
        return JsonResponse({
            'message': 'Product Quantity Added from cart successfully',
            'quantity':cart_item.quantity,
            'total_price':cart_item.get_total_price(),
            'cart_total':cart_item.cart_total(),
            'cart_count':Cart.objects.filter(user=request.user).count(),
        })

misc/ecommerce/web/views/product.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, View
from django.urls import reverse
from web.forms.product import *
from web.helper import renderfile, is_ajax, LogUserActivity
from web.models import Category,Product
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import *
from web.constantvariables import PAGINATION_PERPAGE
from django.shortcuts import get_object_or_404,render,redirect
from django.db import transaction
from django.db.models import Q

class ProductView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context, response = {}, {}
        page = int(request.GET.get('page', 1))
        search_query = request.GET.get('search', '')
        if search_query:
            products = Product.objects.filter(
                name__icontains=search_query,
                is_active=True
            )
        else:
            products = Product.objects.filter(is_active=True)
        
        context['products'], context['current_page'] = products, page
        if is_ajax(request=request):
            response['status'] = True
            response['pagination'] = render_to_string("web/product/pagination.html",context=context,request=request)
            response['template'] = render_to_string("web/product/product_list.html", context, request=request)
            return JsonResponse(response)
        context['form']  = ProductForm()
        return renderfile(request, 'product', 'index', context)
    
class ProductCreate(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context = {
            'form': ProductForm(),
            'item_formset': MultipleImageInputFormFormSet()
        }
        return render(request, 'web/product/product_create.html', context)

    def post(self, request, *args, **kwargs):
        form = ProductForm(request.POST, request.FILES)
        formset = MultipleImageInputFormFormSet(request.POST, request.FILES)

        if form.is_valid() and formset.is_valid():
            product_instance = form.save()

            instances = formset.save(commit=False)
            for instance in instances:
                instance.product = product_instance
                instance.save()
            response = {
                'status': True,
                'message': 'Form submitted successfully!',
            }
            return redirect('web:product')
        else:
            print('--invalid---')
            print('form errors:', form.errors)
            print('formset errors:', formset.errors)
            response = {
                'status': False,
                'form_errors': form.errors,
                'formset_errors': formset.errors,
                'message': 'Form Submission Failed!',
            }
            
            context = {
                'form': form,
                'item_formset': formset
            }
            return render(request, 'web/product/product_create.html', context)

class ProductDelete(LoginRequiredMixin,View):
    def post(self, request, *args, **kwargs):
        id = kwargs.get('pk', None)
        response = {}
        obj = get_object_or_404(Product, id = id)
        obj.delete()
        
        response['status'] = True
        response['message'] = "Product deleted successfully"
        return JsonResponse(response)


class ProductUpdate(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        id = kwargs.get('pk', None)
        data = {}
        obj = get_object_or_404(Product, id = id)
        form = ProductForm(instance=obj)
        item_formset = MultipleImageInputFormFormSet(instance=obj)
        context = {'form': form, 'id': id,'item_formset':item_formset}
        data['status'] = True
        data['title'] = 'Edit Product'
        return render(request, 'web/product/product_create.html', context)
    
    def post(self, request, *args, **kwargs):
        data, response = {} , {}
        id = kwargs.get('pk', None)
        obj = get_object_or_404(Product, id=id)
        form = ProductForm(request.POST or None, instance=obj)
        if form.is_valid():
            form.save()
            response['message'] = "Product updated successfully"
            return redirect('web:product')
        else:
            response['status'] = False
            context = {'form': form}
            response['title'] = 'Edit Product'
            response['valid_form'] = False
            print('form',form.errors)
            return render(request, 'web/product/product_create.html', context)
        

class ProductImageView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        products = ProductMedia.objects.all()
        print("products",products)
        context = {'products_images': products}
        return render(request, 'web/product/product_image_list.html', context)
    

def search(request):
    query = request.GET.get('search', '')

    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query) |
            Q(p_keyword__icontains=query)
        ).distinct()
    else:
        products = Product.objects.all()

    return render(request, 'web/product/search.html', {'products': products})


class ProductVariantView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context, response = {}, {}
        page = int(request.GET.get('page', 1))
        prod_variants = ProductVariant.objects.all()
        context['current_page'] =  page
        context = {'prod_variants': prod_variants}
        if is_ajax(request=request):
            response['status'] = True
            response['pagination'] = render_to_string("web/product/pagination.html",context=context,request=request)
            response['template'] = render_to_string('web/product/product_variant_list.html', context, request=request)
            return JsonResponse(response)
        return render(request, 'web/product/product_variant_index.html', context)
    
class ProductVariantCreate(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context = {
            'form': ProductVariantForm(),
            'id': 0
        }
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'html_form': render_to_string('web/product/product_variant_form.html', context, request=request)})
        return render(request, 'web/product/product_variant_form.html', context)
    
    def post(self,request, *args, **kwargs):
        if is_ajax and request.method == "POST":
            form = ProductVariantForm(request.POST,request.FILES)
            if form.is_valid():
                data = form.save()
                print('data',data)
                response={
                    'status':True,
                    'message': 'Form submitted successfully!',
                }
            else:
                    print('--invalid---')
                    print('form',form.errors)
                    response = {
                        'status': False,
                        'form_errors': form.errors,
                        'message': 'Form Submission Failed!',
                    }
        return redirect('web:product_variant')
    
class ShopView(View):
    def get(self, request, *args, **kwargs):
        context = { 'products': ProductVariant.objects.all() }
        return render(request, 'web/product/shop.html', context)
        

misc/ecommerce/templates/web/product/cart.html
{% extends "web/layout/user_base.html" %} {% load static %} {% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">
        <main>
            <div class="mb-4 pb-4"></div>
            <section class="shop-checkout container">
              <h2 class="page-title">Cart</h2>
              {% if cart_items %}

              <div class="shopping-cart">
                <div class="cart-table__wrapper">
                  <table class="cart-table">
                    <thead>
                      <tr>
                        <th>Product</th>
                        <th></th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for item in cart_items %}
                      <tr>
                        <td>
                          <div class="shopping-cart__product-item">
                           <a href=""><img loading="lazy" src="{{ item.product.image.url }}" width="120" height="120" alt="{{ item.product.name }}" /></a> 
                          </div>
                        </td>
                        <td>
                          <div class="shopping-cart__product-item__detail">
                              <h3>{{ item.product.variant_name }}</h3>
                            <h6>{{ item.product.product.name }}</h6>
                            <ul class="shopping-cart__product-item__options">
                              <li>Price:{{ item.product.sale_price|floatformat:0 }} INR</li>
                            </ul>
                          </div>
                        </td>
                        <td>
                          <div class="qty-control position-relative">
                            <input type="number" id="product-qty{{ item.product.id }}" name="quantity" value="{{item.quantity}}" min="1" class="qty-control__number text-center" readonly>
                            
                          </div>
                        </td>
                        <td>
                          <span class="shopping-cart__subtotal" id="product-price{{ item.product.id }}">{{item.get_total_price|floatformat:2}} INR</span>
                        </td>
                        <td>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  
                </div>
                <div class="shopping-cart__totals-wrapper mt-10">
                  <div class="sticky-content">
                    <div class="shopping-cart__totals">
                      
                      <table class="cart-totals">
                        <tbody>
                        
                          <tr>
                            <th>Total</th>
                            <td id="cart_total">{{cart_total|floatformat:2}} INR</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <div class="mobile_fixed-btn_wrapper">
                    <a href="">
                      <div class="button-wrapper container mt-4">
                        <button class="btn btn-primary btn-checkout">PROCEED TO CHECKOUT</button>
                      </div>
                    </a>
                      {% else %}
                      <img src="{% static 'web/assets/images/cart-empty.png' %}" alt="" width="100%">
                      <a href="{% url 'web:shop' %}">
                        <div class="button-wrapper container text-center">
                          <button class="btn btn-primary btn-checkout">Go Shop</button>
                        </div>
                      </a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </main>
        
          <div class="mb-5 pb-xl-5"></div>
    </div>
</div>
</div>
{% endblock body_block %} 
{% block page_script %}
<script src="{% static 'web/assets/js/product.js' %}?v={% now 'd_m_yH:i:s'%}"></script>
<script src="{% static 'web/assets/js/cart.js' %}?v={% now 'd_m_yH:i:s'%}"></script>

{% endblock page_script %}

misc/ecommerce/templates/web/product/index.html
{% extends "web/layout/user_base.html" %} {% load static %} {% block body_block %}
<div class="content-inner full-screen">
    
    <form method="GET" action="{% url 'web:search' %}">
        {% csrf_token %}
        <input type="text" name="search" placeholder="Search" value="{{ request.GET.search }}">
        <button type="submit" class="button is-success">Search</button>
    </form>
    
    <div class="page-block">
        <input type="hidden" value="{% url 'web:product' %}" id="load_product">
        <div class="d-flex justify-content-between">
            <h1 class="page-block-title">Product List</h1>
            <div>
                <a class="add-product"  href="{% url 'web:create_product' %}">
                    <button>+ Add Product</button>
                </a>
            </div>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>Sl.NO</th>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Description</th>
                        
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody id="product-tbody">
                    {% include 'web/product/product_list.html' %}
                </tbody>
            </table>
        </div>
    </div>

    
    
</div>
</div>
{% endblock body_block %} 
{% block page_script %}
<script src="{% static 'web/assets/js/product.js' %}?v={% now 'd_m_yH:i:s'%}"></script>
{% endblock page_script %}

misc/ecommerce/templates/web/product/product_create.html
{% extends "web/layout/user_base.html" %}
{% load static %}
{% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">

        {% if id %}
            <div class="d-flex justify-content-between">
                <h1 class="page-block-title">Edit Product</h1>
            </div>
        {% else %}
            <div class="d-flex justify-content-between">
                <h1 class="page-block-title">Create Product</h1>
            </div>
        {% endif %}  

        <div>
            <form method="post" action="" id="productInputForm" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="product-form" id="product-out-form-div">
                    <div class="formbg-inner">
                        <input type="hidden" value="{% url 'web:create_product' %}">
                        <div class="edit-product-form row">
                            <div class="col-lg-6">
                                <div class="field padding-bottom--24">
                                    <label for="tool_type">Category</label> {{ form.category }}
                                    <p class="text-danger mt-2 mb-0">{{ form.category.errors.as_text }}</p>
                                </div>
                                <div class="field padding-bottom--24">
                                    <label for="tool_name">Name</label> {{ form.name }}
                                    <p class="text-danger mt-2 mb-0">{{ form.name.errors.as_text }}</p>
                                </div>
                                <div class="field padding-bottom--24">
                                    <label for="tool_context">Description</label> {{ form.description }}
                                    <p class="text-danger mt-2 mb-0">{{ form.description.errors.as_text }}</p>
                                </div>
                                
                                <div class="field padding-bottom--24">
                                    <label for="youtube_link">Keyword</label> {{ form.p_keyword }}
                                    <p class="text-danger mt-2 mb-0">{{ form.p_keyword.errors.as_text }}</p>
                                </div>
                            </div>

                            <div class="col-lg-6">

                                <div class="d-flex justify-content-between">
                                    <h1 class="page-block-title">Add Images</h1>
                                </div>


                                <div class="row">
                                    {{ item_formset.management_form }}
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Image</th>
                                                <th>Set as Default</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for form in item_formset.forms %}
                                            <tr class="form_set_row dynamic-formset">
                                                {% for hidden in form.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                                <td>{{ form.image }}</td>
                                                <td>{{ form.is_default }}</td>

                                                <td></td>
                                            </tr>
                                            {{ form.field_errors }}
                                            {{ form.errors }}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                            
                            <div class="field padding-bottom--24">
                                <input class="product-submit" id="product-submit" type="submit" name="submit" value="Save">
                            </div>
                            
                            
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body_block %}

{% block page_script %}
<script src="{% static 'web/assets/js/formset.js' %}?v={% now 'd_m_yH:i:s' %}"></script>

<script>
    $(document).ready(function () {
        const formsetPrefix = '{{ item_formset.prefix }}';
        $('.form_set_row').formset({
            addText: '<span>Add Image</span>',
            deleteText: 'Remove',
            prefix: formsetPrefix,
            formCssClass: 'dynamic-formset',
            added: function (row) {
                bindUniqueCheckboxHandler();
            }
        });

        function bindUniqueCheckboxHandler() {
            $('.dynamic-formset input[type="checkbox"]').change(function() {
                
                $('.dynamic-formset input[type="checkbox"]').not(this).prop('checked', false);
            });
        }
        bindUniqueCheckboxHandler();
    });
   
    $(document).on('click', '.delete-row', function() {
        $(this).closest('.form_set_row').remove();
        $('.form_set_row').formset('update');
    });

</script>

{% endblock page_script %}

misc/ecommerce/templates/web/product/product_form.html
<div class="formbg-inner">
    <div class="edit-product-form">
        {% if id %}
            <input type="hidden" value="{% url 'web:update_product' id %}" id="form_url" name="form_url">
        {% else %}
            <input type="hidden" value="{% url 'web:create_product' %}" id="form_url" name="form_url">
        {% endif %} 
        <div class="field padding-bottom--24">
            <label for="name">Category</label> {{ form.category }}
            <p class="text-danger mt-2 mb-0">{{ form.category.errors.as_text  }}</p>
        </div>           
        <div class="field padding-bottom--24">
            <label for="name">Name</label> {{ form.name }}
            <p class="text-danger mt-2 mb-0">{{ form.name.errors.as_text  }}</p>
        </div>
        <div class="field padding-bottom--24">
            <label for="name">Description</label> {{ form.description }}
            <p class="text-danger mt-2 mb-0">{{ form.description.errors.as_text  }}</p>
        </div>
        <div class="field padding-bottom--24">
            <label for="name">Keywords</label> {{ form.p_keyword }}
            <p class="text-danger mt-2 mb-0">{{ form.p_keyword.errors.as_text  }}</p>
        </div>
        <div class="field padding-bottom--24">
            <input class="product-submit" id="product-submit" type="submit" name="submit" value="Save">
        </div>
    </div>
</div>

misc/ecommerce/templates/web/product/product_image_list.html
{% extends "web/layout/user_base.html" %}
{% load static %}
{% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">

        {% for i in products_images %}
            <div class="card" style="width: 18rem;">
                {% if i.image %}
                    <img src="{{i.image.url}}" class="card-img-top" alt="...">
                {% else %}
                    <img src="{% static 'web/assets/images/default-avatar.jpg' %}" class="card-img hieght="10" >
                {% endif %}
                
                <div class="card-body">
                <h5 class="card-title">{{i.product}}</h5>
                <h5 class="card-title">{{i.is_default}}</h5>
                </div>
                
            </div>  
        {% endfor %}
        
    </div>
</div>
{% endblock body_block %}

{% block page_script %}
{% endblock page_script %}

misc/ecommerce/templates/web/product/product_list.html
{% load static %}
{% for product in products %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ product.category }}</td>
    <td>{{ product.name }}</td>
    <td>{{ product.description }}</td>
    
    <td>
        {% with default_media=product.get_default_media %}
            {% if default_media %}
                <img src="{{ default_media.image.url }}" class="card-img" style="height: 60px; width: 60px;" alt="icon">
            {% else %}
                <img src="{% static 'web/assets/images/default-avatar.jpg' %}" class="card-img" style="height: 60px; width: 60px;" alt="default icon">
            {% endif %}
        {% endwith %}
    </td>
    <td>
        <a href="{% url 'web:update_product' product.id %}" class="product-edit" id="product-edit"  data-url="">
            <img src="{% static '/web/assets/images/edt_icon.svg' %}" alt="icon">
        </a>

        <a href="javascript:;" onclick="ProductDelete({{ product.id }})">
            <img src="{% static '/web/assets/images/dlt_icon.svg' %}" alt="icon">
        </a>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7">No products found.</td>
</tr>
{% endfor %}

misc/ecommerce/templates/web/product/product_variant_index.html
{% extends "web/layout/user_base.html" %} {% load static %} {% block body_block %}
<div class="content-inner full-screen">
    
    <div class="page-block">
        <input type="hidden" value="" id="load_product">
        <div class="d-flex justify-content-between">
            <h1 class="page-block-title">Product Variant List</h1>
            <div>
                <a class="add-product"  href="{% url 'web:product_variant_create' %}">
                    <button>+ Add Product</button>
                </a>
            </div>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>Sl.NO</th>
                        <th>Product</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Sale Price</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody id="product-tbody">
                    {% include 'web/product/product_variant_list.html' %}
                </tbody>
            </table>
        </div>
    </div>

    
    
</div>
</div>
{% endblock body_block %} 
{% block page_script %}
<script src="{% static 'web/assets/js/product.js' %}?v={% now 'd_m_yH:i:s'%}"></script>
{% endblock page_script %}

misc/ecommerce/templates/web/product/search.html
{% extends "web/layout/user_base.html" %}
{% load static %}
{% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">

        <form method="get" action="{% url 'web:search' %}">
            <input type="text" name="search" placeholder="Search products">
            <button type="submit">Search</button>
        </form>


        {% if products %}
        <h2>Search Results:</h2>
        <ul>
            {% for product in products %}
                <li>
                    <h3>{{ product.name }}</h3>
                    <p>{{ product.description }}</p>
                    <p>Price: {{ product.price }}</p>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No products found.</p>
        {% endif %}
        
    </div>
</div>
{% endblock body_block %}

{% block page_script %}
{% endblock page_script %}